In [37]:
import pandas as pd

In [38]:
train = pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",index_col='enrollee_id')
train.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

# Handling a tsv file

In [39]:
movies = pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/movie_titles_metadata.tsv",sep="\t",names=['sno','name','release_year','rating','votes','genres'])

In [40]:
movies.head()

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']

# header Parameter
to convert the first row into header

In [41]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/test.csv",header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

# User cols Paramter

In [42]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",usecols=['gender','enrollee_id'])

       enrollee_id gender
0             8949   Male
1            29725   Male
2            11561    NaN
3            33241    NaN
4              666   Male
...            ...    ...
19153         7386   Male
19154        31398   Male
19155        24576   Male
19156         5756   Male
19157        23834    NaN

[19158 rows x 2 columns]

# Skip rows and n rows

In [43]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",skiprows=2)

,29725,city_40,0.7759999999999999,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [45]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",nrows=10)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
6,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
7,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
8,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
9,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0

# Encoding paramter

In [46]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",encoding="")

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# skip bad lines (Discontinued)

In [ ]:
# pd.read_csv("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-27/aug_train.csv",error_bad_lines=True)

# d type parameter 
change the datatype of the columns

In [47]:
x = pd.read_csv("/Users/I578070/Desktop/100DaysML/venv/Datasets/dataset-session-27/aug_train.csv",dtype={'enrollee_id': 'int64', 'city_development_index': 'float64', 'education_level': 'category', 'target': 'int8'})

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  category
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int8
dtypes: category(1), float64(1), int64(2), int8(1), object(9)
memory usage: 1.8+ MB

# Handling Dates

In [ ]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-27/IPL Matches 2008-2020.csv",parse_dates=['date'])

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

# Handling n_Values parameter

In [ ]:
pd.read_csv("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-27/aug_train.csv",na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# Loading data sets into chunks

In [ ]:
df = pd.read_csv("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-27/aug_train.csv",chunksize=1000)
for chunk in df:
    print(chunk.shape)
    print(chunk.head())
    # You can process each chunk here
    # For example, you could concatenate them into a single DataFrame
    # or perform some analysis on each chunk.

(1000, 14)
   enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male
1        29725   city_40                   0.776   Male
2        11561   city_21                   0.624    NaN
3        33241  city_115                   0.789    NaN
4          666  city_162                   0.767   Male

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate
1   No relevent experience       no_enrollment        Graduate
2   No relevent experience    Full time course        Graduate
3   No relevent experience                 NaN        Graduate
4  Has relevent experience       no_enrollment         Masters

  major_discipline experience company_size    company_type last_new_job  \
0             STEM        >20          NaN             NaN            1
1             STEM         15        50-99         Pvt Ltd           >4
2             STEM          5          NaN             NaN        never
3  Business Degree         <1          NaN         Pvt Ltd        never
4             STEM        >20        50-99  Funded Startup            4

   training_hours  target
0              36     1.0
1              47     0.0
2              83     0.0
3              52     1.0
4               8     0.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
1000        23392   city_21                   0.624   Male
1001         5879  city_116                   0.743   Male
1002         8861  city_160                   0.920    NaN
1003        21196   city_75                   0.939   Male
1004        10724   city_21                   0.624    NaN

          relevent_experience enrolled_university education_level  \
1000  Has relevent experience       no_enrollment         Masters
1001  Has relevent experience       no_enrollment        Graduate
1002   No relevent experience       no_enrollment         Masters
1003  Has relevent experience       no_enrollment        Graduate
1004  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size         company_type  \
1000             STEM          8      100-500              Pvt Ltd
1001             STEM         13      100-500              Pvt Ltd
1002       Humanities          2          <10  Early Stage Startup
1003             STEM          4       10000+              Pvt Ltd
1004             STEM         11       10000+              Pvt Ltd

     last_new_job  training_hours  target
1000        never             162     1.0
1001            4               6     0.0
1002            1              43     0.0
1003            2              41     0.0
1004            1              40     0.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
2000        26024  city_103                   0.920   Male
2001        20706   city_90                   0.698    NaN
2002         2905  city_103                   0.920   Male
2003        18076   city_16                   0.910   Male
2004        30287   city_21                   0.624   Male

          relevent_experience enrolled_university education_level  \
2000  Has relevent experience       no_enrollment        Graduate
2001  Has relevent experience    Full time course             NaN
2002  Has relevent experience       no_enrollment        Graduate
2003  Has relevent experience       no_enrollment        Graduate
2004  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size    company_type last_new_job  \
2000             STEM         18      500-999         Pvt Ltd           >4
2001              NaN          4      100-500         Pvt Ltd            2
2002             STEM         13      100-500         Pvt Ltd            1
2003             STEM          5      100-500  Funded Startup            3
2004             STEM          7        50-99         Pvt Ltd            1

      training_hours  target
2000             164     0.0
2001              26     1.0
2002              29     0.0
2003              73     0.0
2004              12     1.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
3000        18980  city_136                   0.897   Male
3001        29039  city_103                   0.920   Male
3002        15786  city_103                   0.920   Male
3003        19439   city_21                   0.624    NaN
3004        21298  city_103                   0.920   Male

          relevent_experience enrolled_university education_level  \
3000  Has relevent experience       no_enrollment        Graduate
3001   No relevent experience       no_enrollment        Graduate
3002  Has relevent experience       no_enrollment        Graduate
3003   No relevent experience    Full time course             NaN
3004   No relevent experience    Full time course         Masters

     major_discipline experience company_size   company_type last_new_job  \
3000             STEM         12        50-99        Pvt Ltd            2
3001             STEM        >20       10000+        Pvt Ltd           >4
3002             STEM          4        50-99        Pvt Ltd            1
3003              NaN         <1          NaN            NaN            1
3004             STEM         14       10000+  Public Sector            2

      training_hours  target
3000              59     0.0
3001              32     0.0
3002               9     0.0
3003              37     1.0
3004              52     1.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
4000         9949   city_75                   0.939   Male
4001        28020   city_21                   0.624   Male
4002        22589  city_105                   0.794   Male
4003        16736  city_103                   0.920    NaN
4004        12145   city_57                   0.866    NaN

          relevent_experience enrolled_university education_level  \
4000  Has relevent experience       no_enrollment        Graduate
4001   No relevent experience    Full time course        Graduate
4002  Has relevent experience       no_enrollment         Masters
4003   No relevent experience       no_enrollment         Masters
4004   No relevent experience       no_enrollment     High School

     major_discipline experience company_size         company_type  \
4000             STEM         15        50-99              Pvt Ltd
4001             STEM          2          NaN                  NaN
4002            Other         13          <10  Early Stage Startup
4003             STEM        NaN       10000+                  NaN
4004              NaN         <1          NaN                  NaN

     last_new_job  training_hours  target
4000           >4              35     0.0
4001        never              36     0.0
4002            1               6     0.0
4003          NaN             103     0.0
4004        never             182     0.0
(1000, 14)
      enrollee_id      city  city_development_index  gender  \
5000        18582   city_83                   0.923    Male
5001        25222  city_159                   0.843     NaN
5002         5697   city_61                   0.913  Female
5003         5172   city_21                   0.624    Male
5004         1815   city_27                   0.848    Male

          relevent_experience enrolled_university education_level  \
5000  Has relevent experience       no_enrollment         Masters
5001  Has relevent experience       no_enrollment        Graduate
5002  Has relevent experience       no_enrollment        Graduate
5003   No relevent experience    Full time course        Graduate
5004  Has relevent experience       no_enrollment         Masters

     major_discipline experience company_size company_type last_new_job  \
5000             STEM          9       10000+      Pvt Ltd            4
5001             STEM          7          <10      Pvt Ltd            1
5002             STEM        >20      100-500          NaN            1
5003             STEM          3          NaN          NaN        never
5004             STEM         18       10000+      Pvt Ltd           >4

      training_hours  target
5000             170     0.0
5001             107     0.0
5002               9     0.0
5003              38     1.0
5004              17     1.0
(1000, 14)
      enrollee_id      city  city_development_index  gender  \
6000         3224   city_67                   0.855    Male
6001        21931   city_16                   0.910    Male
6002        23278   city_90                   0.698    Male
6003        22553   city_21                   0.624    Male
6004        25467  city_103                   0.920  Female

          relevent_experience enrolled_university education_level  \
6000  Has relevent experience       no_enrollment        Graduate
6001  Has relevent experience       no_enrollment        Graduate
6002  Has relevent experience    Full time course         Masters
6003  Has relevent experience    Full time course        Graduate
6004   No relevent experience       no_enrollment         Masters

     major_discipline experience company_size    company_type last_new_job  \
6000             STEM          4        50-99   Public Sector            3
6001             STEM        >20        50-99  Funded Startup            1
6002             STEM         14          <10         Pvt Ltd            4
6003             STEM          5        50-99         Pvt Ltd            1
6004             STEM         10        50-99         Pvt Ltd            4

      training_hours  target
6000             158     0.0
6001              84     0.0
6002              28     0.0
6003             135     1.0
6004              56     0.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
7000         1262  city_160                   0.920   Male
7001        29574   city_41                   0.827   Male
7002        31531   city_16                   0.910   Male
7003        13841   city_83                   0.923  Other
7004        14759  city_136                   0.897    NaN

          relevent_experience enrolled_university education_level  \
7000   No relevent experience       no_enrollment        Graduate
7001  Has relevent experience    Part time course        Graduate
7002  Has relevent experience       no_enrollment        Graduate
7003  Has relevent experience       no_enrollment        Graduate
7004  Has relevent experience    Part time course         Masters

     major_discipline experience company_size    company_type last_new_job  \
7000             STEM         17          NaN             NaN            2
7001             STEM          7          <10  Funded Startup            3
7002             STEM         12    1000-4999         Pvt Ltd            4
7003             STEM         10          NaN             NaN           >4
7004             STEM          4          NaN             NaN            2

      training_hours  target
7000              12     0.0
7001              48     0.0
7002             108     0.0
7003             196     1.0
7004             160     0.0
(1000, 14)
      enrollee_id      city  city_development_index gender  \
8000        16315  city_104                   0.924    NaN
8001        11880   city_26                   0.698   Male
8002        13260   city_75                   0.939   Male
8003        13613  city_116                   0.743    NaN
8004        27680  city_103                   0.920   Male

          relevent_experience enrolled_university education_level  \
8000  Has relevent experience       no_enrollment             NaN
8001   No relevent experience    Full time course     High School
8002  Has relevent experience       no_enrollment        Graduate
8003  Has relevent experience       no_enrollment     High School
8004  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size         company_type  \
8000              NaN        >20          NaN                  NaN
8001              NaN          2          NaN                  NaN
8002             STEM          8      100-500              Pvt Ltd
8003              NaN          4          <10  Early Stage Startup
8004             STEM        >20      500-999              Pvt Ltd

     last_new_job  training_hours  target
8000            2              25     0.0
8001            1              15     1.0
8002            2              18     0.0
8003            1              14     0.0
8004            1             188     0.0
(1000, 14)
      enrollee_id      city  city_development_index  gender  \
9000        23173   city_21                   0.624    Male
9001         5325  city_103                   0.920    Male
9002        24197   city_36                   0.893    Male
9003        16924  city_103                   0.920    Male
9004        14803  city_103                   0.920  Female

          relevent_experience enrolled_university education_level  \
9000  Has relevent experience       no_enrollment        Graduate
9001  Has relevent experience       no_enrollment        Graduate
9002  Has relevent experience    Part time course     High School
9003  Has relevent experience       no_enrollment         Masters
9004  Has relevent experience       no_enrollment        Graduate

     major_discipline experience company_size company_type last_new_job  \
9000             STEM          3      500-999      Pvt Ltd            1
9001             STEM          5    1000-4999      Pvt Ltd           >4
9002              NaN         16        10/49      Pvt Ltd            4
9003             Arts          7    1000-4999      Pvt Ltd            3
9004             STEM          4       10000+      Pvt Ltd            2

      training_hours  target
9000             100     0.0
9001               3     0.0
9002              26     0.0
9003              21     0.0
9004              18     0.0
(1000, 14)
       enrollee_id      city  city_development_index gender  \
10000        23427   city_24                   0.698    NaN
10001        17605   city_50                   0.896    NaN
10002        20912   city_73                   0.754    NaN
10003        13948  city_114                   0.926   Male
10004        15205  city_160                   0.920   Male

          relevent_experience enrolled_university education_level  \
10000  No relevent experience                 NaN     High School
10001  No relevent experience       no_enrollment        Graduate
10002  No relevent experience    Full time course        Graduate
10003  No relevent experience       no_enrollment             Phd
10004  No relevent experience    Full time course     High School

      major_discipline experience company_size company_type last_new_job  \
10000              NaN          8          NaN          NaN        never
10001             STEM        >20          NaN          NaN        never
10002             STEM          5          NaN          NaN        never
10003             STEM        >20       10000+      Pvt Ltd            1
10004              NaN          7      100-500      Pvt Ltd            1

       training_hours  target
10000              63     0.0
10001              10     0.0
10002              46     0.0
10003              18     0.0
10004              55     0.0
(1000, 14)
       enrollee_id      city  city_development_index gender  \
11000        18927  city_160                   0.920   Male
11001         5768  city_114                   0.926   Male
11002        23020  city_103                   0.920   Male
11003          775   city_16                   0.910   Male
11004        13404  city_104                   0.924   Male

           relevent_experience enrolled_university education_level  \
11000  Has relevent experience       no_enrollment        Graduate
11001  Has relevent experience       no_enrollment     High School
11002  Has relevent experience    Part time course        Graduate
11003   No relevent experience    Full time course     High School
11004  Has relevent experience       no_enrollment         Masters

      major_discipline experience company_size company_type last_new_job  \
11000             STEM         16       10000+      Pvt Ltd           >4
11001              NaN         12        50-99      Pvt Ltd           >4
11002             STEM          8        50-99      Pvt Ltd            2
11003              NaN          9          NaN          NaN        never
11004             STEM        >20       10000+      Pvt Ltd            4

       training_hours  target
11000              47     0.0
11001              94     0.0
11002              40     0.0
11003              12     0.0
11004             242     0.0
(1000, 14)
       enrollee_id      city  city_development_index gender  \
12000        29186  city_103                   0.920    NaN
12001        10134  city_103                   0.920   Male
12002         6140   city_21                   0.624   Male
12003         7579  city_103                   0.920   Male
12004        23135  city_103                   0.920   Male

           relevent_experience enrolled_university education_level  \
12000  Has relevent experience       no_enrollment         Masters
12001   No relevent experience       no_enrollment        Graduate
12002  Has relevent experience       no_enrollment        Graduate
12003  Has relevent experience       no_enrollment             Phd
12004  Has relevent experience       no_enrollment        Graduate

      major_discipline experience company_size         company_type  \
12000             STEM         16        50-99  Early Stage Startup
12001             STEM         15    1000-4999              Pvt Ltd
12002            Other          3          NaN                  NaN
12003             STEM         14        50-99       Funded Startup
12004  Business Degree          7      100-500       Funded Startup

      last_new_job  training_hours  target
12000            1              73     0.0
12001            1              16     0.0
12002            1              13     1.0
12003            1               4     0.0
12004            1              16     0.0
(1000, 14)
       enrollee_id      city  city_development_index gender  \
13000         5569  city_103                   0.920    NaN
13001         8366  city_103                   0.920   Male
13002         8091   city_21                   0.624   Male
13003        12818  city_162                   0.767    NaN
13004        28662  city_104                   0.924   Male

           relevent_experience enrolled_university education_level  \
13000   No relevent experience    Full time course        Graduate
13001  Has relevent experience       no_enrollment         Masters
13002  Has relevent experience       no_enrollment         Masters
13003  Has relevent experience    Part time course         Masters
13004  Has relevent experience    Part time course         Masters

      major_discipline experience company_size    company_type last_new_job  \
13000             STEM          9          NaN         Pvt Ltd        never
13001             STEM         16      500-999  Funded Startup            1
13002             STEM          6       10000+         Pvt Ltd            3
13003             STEM          6       10000+         Pvt Ltd            1
13004             STEM         17          NaN             NaN           >4

       training_hours  target
13000              31     0.0
13001              67     0.0
13002              55     0.0
13003             114     1.0
13004              25     0.0
(1000, 14)
       enrollee_id      city  city_development_index  gender  \
14000        29120  city_103                   0.920    Male
14001        11420  city_103                   0.920  Female
14002        28511   city_16                   0.910     NaN
14003        19119  city_103                   0.920     NaN

In [ ]:
train = pd.read_json("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-28/train.json")
train.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [ ]:
train.to_csv("/Users/I578070/Desktop/100DaysML/Datasets/dataset-session-28/train.csv",index=False)